cari-pakar web/caripakar/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('caripakar_app/', include('caripakar_app.urls')),
	path('admin/', admin.site.urls),
]

cari-pakar web/caripakar_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('searchresult/', views.searchresult, name='searchresult'),
	path('expertprofile/<int:pk>/', views.expertprofile, name='expertprofile'),
	path('about/', views.about, name = 'about'),
]

cari-pakar web/caripakar_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from decimal import *
from django.core.validators import MinValueValidator, MaxValueValidator

class PerguruanTinggi(models.Model):
    nama_perguruantinggi = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return self.nama_perguruantinggi


class JabatanFungsional(models.Model):
    nama_jabatanfungsional = models.CharField(max_length=100, blank=True, null=True)
    rank = models.IntegerField(blank=True, null=True)
    skor_jabatanfungsional = models.DecimalField(max_digits=12, decimal_places=4, default= Decimal('0.0000'), \
        validators=[MinValueValidator(0), MaxValueValidator(1)])


    def __str__(self):
        return self.nama_jabatanfungsional + ' dengan rank ' + str(self.rank)

    def save(self, *args, **kwargs):
        current_id = self.id
        count_jabfung = JabatanFungsional.objects.count()
        if current_id is None:
            if count_jabfung == 0:
                super(JabatanFungsional, self).save(*args, **kwargs)
            else:
                jabfung_prev = JabatanFungsional.objects.get(rank=count_jabfung)
                if self.skor_jabatanfungsional <= jabfung_prev.skor_jabatanfungsional:
                    raise ValidationError(
                        _('%(value)s skor_jabatanfungsional not valid'),
                        params={'value': self.skor_jabatanfungsional},
                    )
                else:
                    super(JabatanFungsional, self).save(*args, **kwargs)
        else:
            current_rank = self.rank
            try:
                prev_jabfung = JabatanFungsional.objects.get(rank=current_rank-1)
            except JabatanFungsional.DoesNotExist:
                prev_jabfung = None
            try:
                next_jabfung = JabatanFungsional.objects.get(rank=current_rank+1)
            except JabatanFungsional.DoesNotExist:
                next_jabfung = None 
            
            if next_jabfung is None and prev_jabfung is None:
                super(JabatanFungsional, self).save(*args, **kwargs)
            elif next_jabfung is None:
                if prev_jabfung.skor_jabatanfungsional > self.skor_jabatanfungsional:
                    super(JabatanFungsional, self).save(*args, **kwargs)
                else:
                    raise ValidationError(
                        _('%(value)s skor_jabatanfungsional not valid'),
                        params={'value': self.skor_jabatanfungsional},
                    )
            elif prev_jabfung is None:
                if next_jabfung.skor_jabatanfungsional < self.skor_jabatanfungsional:
                    super(JabatanFungsional, self).save(*args, **kwargs)
                else:
                    raise ValidationError(
                        _('%(value)s skor_jabatanfungsional not valid'),
                        params={'value': self.skor_jabatanfungsional},
                    )
            else:
                if prev_jabfung.skor_jabatanfungsional > self.skor_jabatanfungsional and self.skor_jabatanfungsional > next_jabfung.skor_jabatanfungsional:
                    super(JabatanFungsional, self).save(*args, **kwargs)
                else:
                    raise ValidationError(
                        _('%(value)s skor_jabatanfungsional not valid'),
                        params={'value': self.skor_jabatanfungsional},
                    )


    class Meta:
        ordering = ('rank', )

class Keahlian(models.Model):
    nama_keahlian = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.nama_keahlian


class ProgramStudi(models.Model):
    nama_programstudi = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.nama_programstudi


class ProgramStudiKeahlian(models.Model):
    programstudi = models.ForeignKey(ProgramStudi, on_delete=models.CASCADE, blank=True, null= True)
    keahlian = models.ForeignKey(Keahlian, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.programstudi.nama_programstudi + ' dengan keahlian ' + self.keahlian.nama_keahlian
        

class Dosen(models.Model):
    perguruantinggi = models.ForeignKey(PerguruanTinggi, on_delete=models.CASCADE, blank=True, null=True)
    jabatanfungsional = models.ForeignKey(JabatanFungsional, on_delete=models.CASCADE, blank=True, null=True)
    nama_dosen = models.CharField(max_length=80, blank=True, null=True)
    programstudi = models.ForeignKey(ProgramStudi, on_delete=models.CASCADE, blank=True, null= True)
    url = models.CharField(max_length=255, blank=True, null=True)
    total_jumlah_pengajaran = models.IntegerField(default=0)
    total_jumlah_penelitian = models.IntegerField(default=0)
    total_jumlah_proyek = models.IntegerField(default=0)

    def __str__(self):
        return self.nama_dosen + ' di ' + self.perguruantinggi.nama_perguruantinggi

class DosenJumlahPengajaran(models.Model):
    dosen = models.ForeignKey(Dosen, on_delete=models.CASCADE)
    keahlian = models.ForeignKey(Keahlian, on_delete=models.CASCADE)
    jumlah_pengajaran = models.IntegerField(default=0)

class DosenJumlahPenelitian(models.Model):
    dosen = models.ForeignKey(Dosen, on_delete=models.CASCADE)
    keahlian = models.ForeignKey(Keahlian, on_delete=models.CASCADE)
    jumlah_penelitian = models.IntegerField(default=0)

class DosenJumlahProyek(models.Model):
    dosen = models.ForeignKey(Dosen, on_delete=models.CASCADE)
    keahlian = models.ForeignKey(Keahlian, on_delete=models.CASCADE)
    jumlah_proyek = models.IntegerField(default=0)

class Jenjang(models.Model):
    nama_jenjang = models.CharField(max_length=255)
    rank = models.IntegerField(unique=True, default=0, null=True)
    skor_jenjang = models.DecimalField(max_digits=12, decimal_places=4, default= Decimal('0.0000'), \
        validators=[MinValueValidator(0), MaxValueValidator(1)])    

    def __str__(self):
        return self.nama_jenjang + ' rank ' + str(self.rank)

    def save(self, *args, **kwargs):
        current_id = self.id
        count_jenjang = Jenjang.objects.count()
        if current_id is None:
            if count_jenjang == 0:
                super(Jenjang, self).save(*args, **kwargs)
            else:
                jenjang_prev = Jenjang.objects.get(rank=count_jenjang)
                if self.skor_jenjang <= jenjang_prev.skor_jenjang:
                    raise ValidationError(
                        _('%(value)s skor_jenjang not valid'),
                        params={'value': self.skor_jenjang},
                    )
                else:
                    super(Jenjang, self).save(*args, **kwargs)
        else:
            current_rank = self.rank
            try:
                prev_jenjang = Jenjang.objects.get(rank=current_rank-1)
            except Jenjang.DoesNotExist:
                prev_jenjang = None
            try:
                next_jenjang = Jenjang.objects.get(rank=current_rank+1)
            except Jenjang.DoesNotExist:
                next_jenjang = None
            
            if next_jenjang is None and prev_jenjang is None:
                super(Jenjang, self).save(*args, **kwargs)
            elif next_jenjang is None:
                if prev_jenjang.skor_jenjang > self.skor_jenjang:
                    super(Jenjang, self).save(*args, **kwargs)
                else:
                    raise ValidationError(
                        _('%(value)s skor_jenjang not valid'),
                        params={'value': self.skor_jenjang},
                    )
            elif prev_jenjang is None:
                if next_jenjang.skor_jenjang < self.skor_jenjang:
                    super(Jenjang, self).save(*args, **kwargs)
                else:
                    raise ValidationError(
                        _('%(value)s skor_jenjang not valid'),
                        params={'value': self.skor_jenjang},
                    )
            else:
                if prev_jenjang.skor_jenjang > self.skor_jenjang and self.skor_jenjang > next_jenjang.skor_jenjang:
                    super(Jenjang, self).save(*args, **kwargs)
                else:
                    raise ValidationError(
                        _('%(value)s skor_jenjang not valid'),
                        params={'value': self.skor_jenjang},
                    )

    class Meta:
        ordering = ('rank', )

class Gelar(models.Model):
    nama_gelar = models.CharField(max_length=80, blank=True, null=True)
    jenjang = models.ForeignKey(Jenjang, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama_gelar


class MataKuliah(models.Model):
    keahlian = models.ForeignKey(Keahlian, on_delete=models.SET_NULL, blank=True, null=True)
    nama_matakuliah = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.nama_matakuliah


class Penelitian(models.Model):
    keahlian = models.ForeignKey(Keahlian, on_delete=models.SET_NULL, blank=True, null=True)
    dosen = models.ForeignKey(Dosen, on_delete=models.CASCADE, blank=True, null=True)
    perguruantinggi = models.ForeignKey(PerguruanTinggi, on_delete=models.SET_NULL, blank=True, null=True)
    judul_penelitian = models.CharField(max_length=200, blank=True, null=True)
    tahun = models.IntegerField(blank=True, null=True)

    def __str__(self):

cari-pakar web/caripakar_app/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.db.models import F

from .models import Keahlian, DosenSkor, Dosen
from .utils import get_all_keahlian_by_dosen
import pickle


with open('./caripakar_app/KlasifikasiPakar.sav', 'rb') as model_file:
    loaded_model = pickle.load(model_file)

with open('./caripakar_app/tvect.sav', 'rb') as tvect_file:
    tvect = pickle.load(tvect_file)


# Create your views here.
def index(request):
    
    if request.method == 'POST':
        query = request.POST['search-data']
        return HttpResponseRedirect(reverse('searchresult') + '?q=' + query)
    else:
        template_name = 'index.html'
        return render(request, template_name, {'nbar': 'home'})

def searchresult(request):
    template_name = 'searchresult.html'
    query = request.GET['q'].lower()
    id_keahlian = request.GET['keahlian'] if 'keahlian' in request.GET else None
    bobot_pendidikan = request.GET['skor-pendidikan'] if 'skor-pendidikan' in request.GET else 50
    bobot_penelitian = request.GET['skor-penelitian'] if 'skor-penelitian' in request.GET else 50
    bobot_pengajaran = request.GET['skor-pengajaran'] if 'skor-pengajaran' in request.GET else 50
    bobot_jabatan = request.GET['skor-jabatan'] if 'skor-jabatan' in request.GET else 50
    bobot_proyek = request.GET['skor-proyek'] if 'skor-proyek' in request.GET else 50
    prediction = loaded_model.predict(tvect.transform([query]))[0]
    try:
        if 'keahlian' in request.GET:
            keahlian = Keahlian.objects.get(pk=id_keahlian)
        else:
            keahlian = Keahlian.objects.get(nama_keahlian=prediction)
        keahlian_list = Keahlian.objects.all()
        dosen_recommendation_list = DosenSkor.objects.filter(keahlian=keahlian).annotate(
            total_skor=(F('z_skor_pendidikan') * bobot_pendidikan + F('z_skor_proyek') * bobot_proyek \
            + F('z_skor_pengajaran') * bobot_pengajaran + F('z_skor_penelitian') \
            * bobot_pendidikan) + F('z_skor_jabatan') * bobot_jabatan).order_by('-total_skor')[:5]
        dosen_recommendation_list = [(dosen_skor.dosen, get_all_keahlian_by_dosen(
            dosen_skor.dosen, \
            bobot_pendidikan, \
            bobot_penelitian, \
            bobot_pengajaran, \
            bobot_proyek, \
            bobot_jabatan)) \
            for dosen_skor in dosen_recommendation_list]
        print(dosen_recommendation_list)
        return render(request, template_name, {
            'nbar': 'home', 
            'keahlian_list': keahlian_list, 
            'keahlian': keahlian, 
            'skor_pengajaran': bobot_pengajaran,
            'skor_penelitian': bobot_penelitian,
            'skor_pendidikan': bobot_pendidikan,
            'skor_jabatan': bobot_jabatan,
            'skor_proyek': bobot_proyek,
            'query_param': query,
            'dosen_recommendation_list': dosen_recommendation_list })
    except Keahlian.DoesNotExist:
        raise Http404


def expertprofile(request, pk):
    template_name = 'expertprofile.html'
    try:
        dosen = Dosen.objects.get(pk=pk)
        return render(request, template_name, {'nbar': 'home', 'dosen': dosen})
    except Dosen.DoesNotExist:
        raise Http404
    

    # TO-DO

def about(request):
    template_name = 'about.html'
    return render(request, template_name, {'nbar': 'about'})

cari-pakar web/caripakar_app/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Cari Pakar Dosen Indonesia</title>
{% endblock title %}

{% block content %}
<div class="pd-20">
	<p>
		Hasil tugas akhir berbentuk web yang terdiri dari dua fungsi utama: <br>
		1. Mapping permasalahan dengan bidang keahlian terkait <br>
		2. Mapping bidang keahlian terkait dengan pakar yang sesuai (lingkup dosen) <br><br>
		By: Dharma Kurnia Septialoka <br>
		Supervised by: Pak Windy Gambetta
	</p>
</div>

{% endblock content %}

cari-pakar web/caripakar_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}
	{% endblock title %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/helper.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/caripakar.css' %}">
</head>

{% block localcss %}
{% endblock localcss %}

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'content/logo.png' %}" alt="" class="img-logo"></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item {% if nbar == 'home' %}active{% endif %}">
					<a class="nav-link" href="{% url 'index' %}">Beranda <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item {% if nbar == 'about' %}active{% endif %}">
					<a class="nav-link" href="{% url 'about' %}">Tentang</a>
				</li>
			</ul>
		</div>
	</nav>
	{% block content %}
	{% endblock %}
</body>
{% block scripts %}
<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
{% endblock scripts %}

{% block localscript %}
{% endblock localscript %}
</html>

cari-pakar web/caripakar_app/templates/expertprofile.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
<title>Cari Pakar Dosen Indonesia</title>
{% endblock title %}

{% block localcss %}
{% endblock localcss %}

{% block content %}

<div class="container pd-t-20">
	<h3>{{ dosen.nama_dosen }}, {{ dosen.jabatanfungsional.nama_jabatanfungsional }}, {{ dosen.perguruantinggi.nama_perguruantinggi}}</h3>
	<hr>
	<p>Program Studi: {{ dosen.programstudi.nama_programstudi }}<br>
	Jabatan Fungsional: {{ dosen.jabatanfungsional.nama_jabatanfungsional }}</p>
	
	<ul class="nav nav-tabs" role="tablist">
		<li class="nav-item">
			<a class="nav-link active" data-toggle="tab" href="#pendidikan">Riwayat Pendidikan</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" data-toggle="tab" href="#pengajaran">Riwayat Pengajaran</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" data-toggle="tab" href="#penelitian">Riwayat Penelitian</a>
		</li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#proyek">Riwayat Pengabdian Masyarakat</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="pendidikan" class="container tab-pane active"><br>
     <table class="table table-bordered">
      <thead>
        <tr>
          <th>No</th>
          <th>Perguruan Tinggi</th>
          <th>Gelar Akademik</th>
          <th>Tanggal Ijazah</th>
          <th>Jenjang</th>
        </tr>
      </thead>
      <tbody>
        {% for dosengelar in dosen.dosengelar_set.all %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ dosengelar.perguruantinggi.nama_perguruantinggi }}</td>
          <td>{{ dosengelar.gelar.nama_gelar }}</td>
          <td>{{ dosengelar.tahun_ijazah }}</td>
          <td>{{ dosengelar.gelar.jenjang.nama_jenjang }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div id="pengajaran" class="container tab-pane fade"><br>
   <table class="table table-bordered">
    <thead>
      <tr>
        <th>No</th>
        <th>Nama Mata Kuliah</th>
        <th>Perguruan Tinggi</th>
        <th>Jumlah Semester Pengajaran</th>
      </tr>
    </thead>
    <tbody>
      {% for dosenmatakuliah in dosen.dosenmatakuliah_set.all %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ dosenmatakuliah.matakuliah.nama_matakuliah }}</td>
        <td>{{ dosenmatakuliah.perguruantinggi.nama_perguruantinggi }}</td>
        <td>{{ dosenmatakuliah.jumlah_pengajaran }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div id="penelitian" class="container tab-pane fade">
 <table class="table table-bordered">
  <thead>
    <tr>
      <th>No</th>
      <th>Judul Penelitian</th>
      <th>Bidang Ilmu</th>
      <th>Lembaga</th>
      <th>Tahun</th>
    </tr>
  </thead>
  <tbody>
    {% for penelitian in dosen.penelitian_set.all %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ penelitian.judul_penelitian }}</td>
      <td>{{ penelitian.keahlian.nama_keahlian }}</td>
      <td>{{ penelitian.perguruantinggi.nama_perguruantinggi }}</td>
      <td>{{ penelitian.tahun }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
<div id="proyek" class="container tab-pane fade">
 	<table class="table table-bordered">
	  	<thead>
	    <tr>
	      <th>No</th>
	      <th>Judul Proyek</th>
	      <th>Bidang Ilmu</th>
	      <th>Pengguna Jasa</th>
	      <th>Tahun</th>
	    </tr>
	  	</thead>
	  	<tbody>
	    {% for proyek in dosen.proyek_set.all %}
	    <tr>
	      <td>{{ forloop.counter }}</td>
	      <td>{{ proyek.judul_proyek }}</td>
	      <td>{{ proyek.keahlian.nama_keahlian }}</td>
	      <td>{{ proyek.pengguna_jasa }}</td>
	      <td>{{ proyek.tahun }}</td>
	    </tr>
	    {% endfor %}
	  	</tbody>
	</table>
</div>
</div>

</div>

{% endblock content %}
{% block localscript %}
<script>
	$(document).ready(function(){
		$(".btn-pref .btn").click(function () {
			$(".btn-pref .btn").removeClass("btn-primary").addClass("btn-default");
			$(this).removeClass("btn-default").addClass("btn-primary");  
		});
	});
</script>
{% endblock localscript %}

cari-pakar web/caripakar_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Cari Pakar Dosen Indonesia</title>
{% endblock title %}

{% block content %}
<div class="jumbotron">
	<h1 class="display-4">Cari Pakar dari Dosen Indonesia</h1>
	<p class="lead">Referensi dosen-dosen terbaik di bidangnya</p>
	<hr class="my-4">
	<p>Selamat datang di sistem pencarian pakar dari kumpulan dosen perguruan tinggi di Indonesia!<br> Kamu tinggal ketik persoalan yang ingin kamu selesaikan dan kami akan merekomendasikan pakar yang tepat untuk persoalan kamu.</p>
</div>

<div class="container">
	<form method="POST" action="{% url 'index' %}">
		{% csrf_token %}
		<div class="form-group">
			<label for="problemForm">Tuliskan permasalahan atau bidang keahlian yang kamu cari disini:</label>
			<textarea name="search-data" class="form-control" id="problemForm" rows="5" placeholder="Semakin lengkap semakin jelas. Misal: Pengembangan Internet of Things (IoT) untuk Tour Guide"></textarea>
		</div>
		<div class="text-center">
			<!-- <a href="{% url 'searchresult' %}"><button class="btn btn-primary btn-wide" type="submit">Cari</button></a> -->
			<button type="submit" class="btn btn-primary btn-wide">Cari</button>
		</div>
	</form>
</div>

{% endblock content %}

cari-pakar web/caripakar_app/templates/searchresult.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
<title>Cari Pakar Dosen Indonesia</title>
{% endblock title %}

{% block localcss %}
<link rel="stylesheet" type="text/css" href="{% static 'fontawesome/web-fonts-with-css/css/fontawesome-all.min.css' %}">
{% endblock localcss %}

{% block content %}
<div class="container pd-t-20">
	<h6>Bidang keahlian yang kamu cari adalah: <span class="text-primary">{{ keahlian }}</span></h6>
	<div class="other-expertise pd-t-20">
		Pencarian tidak sesuai?<br>
		Pilih bidang keahlian lainnya
		<form action="{{ request.get_full_path }}" method="GET">
		<input type="hidden" name="q" value="{{ query_param }}" />
		<div class="form-group">	
			<select class="form-control" name="keahlian" id="expertise" style="max-width: 320px;">
				{% for keahlian_x in keahlian_list %}
					{% if keahlian_x == keahlian %}
						<option value="{{ keahlian_x.id }}" selected>{{ keahlian_x.nama_keahlian }}</option>
					{% else %}
						<option value="{{ keahlian_x.id }}">{{ keahlian_x.nama_keahlian }}</option>
					{% endif %}
				{% endfor %}
			</select>
		</div>
	</div>

	<div class="expertise-weight pd-t-20 pd-b-20">
		<h6>Aspek apa yang paling penting? Berikan bobot yang sesuai menurut kamu</h6>
		<!-- <form action="{{ request.get_full_path }}" method="GET"> -->
			<!-- <input type="hidden" name="q" value="{{ query_param }}" /> -->
			<div class="row">
				<div class="col-3 pd-t-20	">
					Pendidikan
				</div>
				<div class="col-6">
					<div class="range range-primary">
						<input type="range" name="skor-pendidikan" min="1" max="100" value="{% if skor_pendidikan %}{{ skor_pendidikan }}{% else %}50{% endif %}" onchange="rangePrimary.value=value">
						<output id="rangePrimary">{% if skor_pendidikan %}{{ skor_pendidikan }}{% else %}50{% endif %}</output>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
			<div class="row">
				<div class="col-3 pd-t-20	">
					Penelitian
				</div>
				<div class="col-6">
					<div class="range range-success">
						<input type="range" name="skor-penelitian" min="1" max="100" value="{% if skor_penelitian %}{{ skor_penelitian }}{% else %}50{% endif %}" onchange="rangeSuccess.value=value">
						<output id="rangeSuccess">{% if skor_penelitian %}{{ skor_penelitian }}{% else %}50{% endif %}</output>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
			<div class="row">
				<div class="col-3 pd-t-20	">
					Pengajaran
				</div>
				<div class="col-6">
					<div class="range range-info">
						<input type="range" name="skor-pengajaran" min="1" max="100" value="{% if skor_pengajaran %}{{ skor_pengajaran }}{% else %}50{% endif %}" onchange="rangeInfo.value=value">
						<output id="rangeInfo">{% if skor_pengajaran %}{{ skor_pengajaran }}{% else %}50{% endif %}</output>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-3 pd-t-20	">
					Jabatan
				</div>
				<div class="col-6">
					<div class="range range-danger">
						<input type="range" name="skor-jabatan" min="1" max="100" value="{% if skor_jabatan %}{{ skor_jabatan }}{% else %}50{% endif %}" onchange="rangeDanger.value=value">
						<output id="rangeDanger">{% if skor_jabatan %}{{ skor_jabatan }}{% else %}50{% endif %}</output>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
			<div class="row">
				<div class="col-3 pd-t-20	">
					Pengabdian Masyarakat
				</div>
				<div class="col-6">
					<div class="range range-info">
						<input type="range" name="skor-proyek" min="1" max="100" value="{% if skor_proyek %}{{ skor_proyek }}{% else %}50{% endif %}" onchange="rangeInfo.value=value">
						<output id="rangeInfo">{% if skor_proyek %}{{ skor_proyek }}{% else %}50{% endif %}</output>
					</div>
				</div>
			</div>
			<div class="search-again text-center pd-t-20 pd-b-20">
				<button type="submit" class="btn btn-outline-primary btn-lg">Cari Ulang</button>
			</div>
		</form>
	</div>

	
</div>


<div class="content">
	<div class="container">
		<div class="text-center text-title pd-t-20 pd-b-40">
			<h2>Rekomendasi Pakar</h2>
			<div class="group-shape">
				<div id="element1">  <hr></div>
				<div id="element2">  <div class="diamond-small"></div> </div>
				<div id="element3">  <hr> </div>
			</div>
			<div class="container pd-b-20">
				<div class="row text-center">
					{% for dosen, keahlian_list in dosen_recommendation_list %}
						<div class="col-md-4 col-sm-6 mg-b-20 pd-t-20">
							<div class="back-box">
								<div class="prod-text">
									<h4 class="text-bold">{{ dosen.nama_dosen }}</h4>
									<i class="fas fa-university"></i> {{ dosen.perguruantinggi.nama_perguruantinggi }}<br>
									<i class="fas fa-star"></i>
										{% for keahlian, skor in keahlian_list %}
											<br>- {{ keahlian.nama_keahlian }} - {{ skor|floatformat:2 }}
										{% endfor %}
									<br>
									<i class="fas fa-graduation-cap"></i>
										{% for dosengelar in dosen.dosengelar_set.all %}
											{{ dosengelar.gelar.nama_gelar }}
										{% endfor %}
									<div class="pd-t-20"></div>
									<a href="{% url 'expertprofile' dosen.id %}">
										<button class="btn btn-primary" type="button">
										Lihat Profil
										</button>
									</a>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</div>



<!-- add pagination here  -->


{% endblock content %}